version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://admin:senha123@mongodb:27017/mydb?authSource=admin
      - PORT=3000
      - JWT_SECRET=breykey2025
      - MAX_LOGIN_ATTEMPT=5
      - LOGIN_TIMEOUT=1
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=senha123
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
